package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "crc32c",
    srcs = ["crc32c.cc"],
    deps = [
        "@com_google_crc32c//:crc32c",
        "@com_google_absl//absl/strings",
    ],
)
