package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_leveldb//:leveldb",
    ],
)
